#!/usr/bin/env ruby
# frozen_string_literal: true

require 'date'

def front_matter(page_name, page_description, page_filename)
  [
    '---',
    'layout: page',
    "title: #{page_name}",
    "decscription: #{page_description}",
    "permalink: /#{page_filename.gsub('.md', '')}/",
    "update: #{DateTime.now.strftime('%Y-%m-%d')}",
    '---',
    ''
  ].join "\n"
end

def filename(page_name)
  "#{page_name.downcase.gsub(' ', '-')}.md"
end

def generate_file(page_filename, header)
  path = File.join Dir.pwd, page_filename
  if File.exist? path
    puts "Error: page exists #{path}"
    exit 1
  end
  File.open(path, 'w') { |file| file.write header }
end

print 'new page name? '
page_name = gets.strip
print 'new page description? '
page_description = gets.strip
page_filename = filename page_name
puts "page name: #{page_filename}"
puts "page description: #{page_description}"
header = front_matter page_name, page_description, page_filename
puts header
generate_file page_filename, header
puts "created #{page_filename}"
